/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Principal.PrincipalSoft;
import Producto.Productos;

/**
 *
 * @author kevin
 */
public class ProductosView extends javax.swing.JFrame {

    /**
     * Creates new form ProductosView
     */
    public ProductosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        referenciaProductosLabel = new javax.swing.JLabel();
        referenciaProductosField = new javax.swing.JTextField();
        nombreProductosLabel = new javax.swing.JLabel();
        nombreProductosField = new javax.swing.JTextField();
        cantidadProductosLabel = new javax.swing.JLabel();
        cantidadProductosField = new javax.swing.JTextField();
        btnGuardarFormProductos = new javax.swing.JButton();
        btnSalirFormProductos = new javax.swing.JButton();
        consultarProductosField = new javax.swing.JTextField();
        btnConsultarFormProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        referenciaProductosLabel.setText("Referencia del Producto: ");

        referenciaProductosField.setToolTipText("Escribe aqui");
        referenciaProductosField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                referenciaProductosFieldPropertyChange(evt);
            }
        });

        nombreProductosLabel.setText("Nombre del Producto: ");

        cantidadProductosLabel.setText("Cantidad del Producto: ");

        btnGuardarFormProductos.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnGuardarFormProductos.setText("Guardar");
        btnGuardarFormProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFormProductosActionPerformed(evt);
            }
        });

        btnSalirFormProductos.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnSalirFormProductos.setText("Salir");
        btnSalirFormProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirFormProductosActionPerformed(evt);
            }
        });

        consultarProductosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarProductosFieldActionPerformed(evt);
            }
        });

        btnConsultarFormProductos.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        btnConsultarFormProductos.setText("Consultar");
        btnConsultarFormProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarFormProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(nombreProductosLabel)
                                    .addGap(35, 35, 35))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(referenciaProductosLabel)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cantidadProductosLabel)
                                .addGap(30, 30, 30))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarFormProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalirFormProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenciaProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnConsultarFormProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenciaProductosLabel)
                    .addComponent(referenciaProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProductosLabel)
                    .addComponent(nombreProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadProductosLabel)
                    .addComponent(cantidadProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarFormProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarProductosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalirFormProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarFormProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void referenciaProductosFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_referenciaProductosFieldPropertyChange
        // este no
    }//GEN-LAST:event_referenciaProductosFieldPropertyChange

    private void btnGuardarFormProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFormProductosActionPerformed
        int referenciasProductos = Integer.parseInt(referenciaProductosField.getText());
        String nombresProductos = nombreProductosField.getText();
        int cantidadProductos = Integer.parseInt(cantidadProductosField.getText());
        PrincipalSoft.registrarProductos(referenciasProductos, nombresProductos, cantidadProductos);
        
        //Luego de registrar valores en el objeto y dejar los textfield en blanco
        referenciaProductosField.setText("");
        nombreProductosField.setText("");
        cantidadProductosField.setText("");
    }//GEN-LAST:event_btnGuardarFormProductosActionPerformed

    private void btnSalirFormProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirFormProductosActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirFormProductosActionPerformed

    private void consultarProductosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarProductosFieldActionPerformed
        // este no
    }//GEN-LAST:event_consultarProductosFieldActionPerformed

    private void btnConsultarFormProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarFormProductosActionPerformed
        //boton consultar, lee el valor que hay en el campo consultar, y luego usa ese valor para llamar al metodo consultar en PrincipalSoft
        int referenciaProductos = Integer.parseInt(consultarProductosField.getText());
        PrincipalSoft.consultarProductos(referenciaProductos);
    }//GEN-LAST:event_btnConsultarFormProductosActionPerformed
    public void imprimirProductos(Productos productos){
        //Recibe como parametro el vector y cada uno de los campos se los asigna a los field correspondientes
        this.referenciaProductosField.setText(Integer.toString(productos.getReferenciasProductos()));
        this.nombreProductosField.setText(productos.getNombresProductos());
        this.cantidadProductosField.setText(Integer.toString(productos.getCantidadProductos()));
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarFormProductos;
    private javax.swing.JButton btnGuardarFormProductos;
    private javax.swing.JButton btnSalirFormProductos;
    private javax.swing.JTextField cantidadProductosField;
    private javax.swing.JLabel cantidadProductosLabel;
    private javax.swing.JTextField consultarProductosField;
    private javax.swing.JTextField nombreProductosField;
    private javax.swing.JLabel nombreProductosLabel;
    private javax.swing.JTextField referenciaProductosField;
    private javax.swing.JLabel referenciaProductosLabel;
    // End of variables declaration//GEN-END:variables
}
